# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('playerTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
        ),
    ]
