# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerSalary',
            field=models.IntegerField(default=500000),
        ),
    ]
