# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_playersalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamPayroll',
            field=models.IntegerField(default=500000),
        ),
    ]
