# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_teampayroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerapg',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='player',
            name='playerppg',
            field=models.FloatField(default=10.5),
        ),
        migrations.AddField(
            model_name='player',
            name='playerrpg',
            field=models.FloatField(default=3.5),
        ),
    ]
